### PR TITLE
Add Heroism and Valor Points and fixed the worldserver "Error"

### PR DESCRIPTION
**Pull request by Valoriaz**

### CODE REVIEW

**Comment by Helias** [comment]
hey, to trigger the pipeline you don't need to close and reopen the PR, you can just push the commit to your PR branch (master in this case)

**Comment by Helias** [comment]
weird issue
```
In file included from /home/runner/work/mod-emblem-transfer/mod-emblem-transfer/var/build/obj/googletest/googletest-src/googlemock/src/gmock-all.cc:39:
In file included from /home/runner/work/mod-emblem-transfer/mod-emblem-transfer/var/build/obj/googletest/googletest-src/googlemock/include/gmock/gmock.h:58:
In file included from /home/runner/work/mod-emblem-transfer/mod-emblem-transfer/var/build/obj/googletest/googletest-src/googlemock/include/gmock/gmock-function-mocker.h:43:
/home/runner/work/mod-emblem-transfer/mod-emblem-transfer/var/build/obj/googletest/googletest-src/googlemock/include/gmock/gmock-spec-builders.h:1713:47: error: unused parameter 'os' [-Werror,-Wunused-parameter]
                                std::ostream& os) {
                                              ^
1 error generated.
make[2]: *** [googletest/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make:76: googletest/googletest-build/googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1534: googletest/googletest-build/googlemock/CMakeFiles/gmock.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 11%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Vector4.cpp.o
[ 11%] Linking CXX static library libg3dlib.a
[ 11%] Built target g3dlib
make: *** [Makefile:146: all] Error 2
```

I restarted the build btw

**Comment by Valoriaz** [comment]
i know..i tried some code adjustments..but this error come everytime as well..

**Comment by Helias** [comment]
try to update your branch with master branch now

**Comment by Helias** [comment]
may this can fix the issue https://github.com/google/googletest/pull/3859

**Comment by Valoriaz** [comment]
dosnt change any

**Comment by Helias** [comment]
this issue is affecting all AC PRs, I am finding a solution

**Comment by Helias** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/11902

**Comment by Valoriaz** [comment]
How can i change the File ?

**Comment by Helias** [comment]
wait that my azerothcore PR will be merged to the master branch, you don't need to do anything, only wait 👍

**Comment by Valoriaz** [comment]
Alright..but thanks a lot mate 👌👍

**Comment by Helias** [comment]
done ✅

**Pull request merged**
